#!/bin/sh -e
chmod 755 /usr/bin/ostorybook
chmod 755 /usr/share/ostorybook/oStorybook.jar
if [ "$1" = "configure" ] && [ -x "`which update-mime-database 2>/dev/null`" ]; then
	update-mime-database /usr/share/mime
fi
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/oStorybook-icon.png
fi
				